### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by RoyJacobs**
I've fixed the build for the current version of Yoga and added it as a submodule.

Also I've added support for the YGValue API, since that was now needed in a number of places instead of passing in raw floats.

### CODE REVIEW

**Comment by RoyJacobs** [comment]
I'm not 100% sure if these fixes work in all situations, but at least when "getting" a property they now return the expected values, instead of NaN (= YGValueUndefined, I suppose). Feel free to only use the first commit :)

**Comment by dobrite** [comment]
Thanks for the PR! I'll poke at it over the weekend. I wasn't sure how to handle the yoga repo, but a git-submodule is better than what I had (obviously).

I also intend to re-license this under the MIT/APACHE licenses to be in-line with Rust itself. Would you be ok with that for what I do pull in?

Also, I'm curious what you're using yoga for 😄

**Comment by dobrite** [comment]
I briefly looked at this and it seems I missed a huge swath of functionality so thanks for pointing that out! I also saw [this wrapper](https://github.com/bschwind/yoga-rs) which looks much nicer and more complete atm.

I'm also sort of wondering how far bindgen would get me. The idea behind this repo (i.e. why it is named `yoga-wrapper-rs` and not `yoga-rs`) is for it to be as bare-bones of a wrapper as possible.  As in make no attempt to make it "safe" in the Rust sense. I'll be sure to update the README with that.

It'll let someone else write their own higher-level wrapper, which is what it looks like bschwind is doing and what [this repo](https://github.com/dobrite/yoga-rs) aims to do at some point. Who knows if I'll ever get there. I certainly have a lot of projects going 😆 

I still won't have proper time to work on the missing stuff until the weekend, unfortunately, but I intend on getting to it.

**Comment by RoyJacobs** [comment]
Hi! Yes, indeed I found bschwind's wrapper which (for my purposes) is a bit more aligned with how I want to use Yoga. It's also missing some stuff, notably the getters, but for now it's ok.

Btw, the reason I'm using Yoga is because as an exercise I'm working on getting Webrender working together with Yoga to form a basis for a GUI library. I don't have anything particularly useful running as of yet, but it seems like it could work. :)

**Comment by dobrite** [comment]
I pulled in your first change and added the missing functions. This lib isn't much more than a manual bindgen at this point I'm afraid. Thank you for your PR and input!

**Pull request closed without merging**
